# Generated by Django 4.0.7 on 2022-08-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_subscription_to_user_alter_subscription_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='userid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='from_user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='social.user'),
            preserve_default=False,
        ),
    ]
