# Generated by Django 4.0.7 on 2022-08-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
